name="household_power_consumption.txt"
data <- read.csv2(name)
data[,1] <- as.Date(data[,1], "%d/%m/%Y")
date1 <- as.Date("2007-02-01")
date2 <- as.Date("2007-02-02")
m <- subset(data, Date >= date1 & Date <= date2)
m[,3] <- as.numeric(m[,3])
m[,7] <- as.numeric(m[,7])
m[,8] <- as.numeric(m[,8])
m[,9] <- as.numeric(m[,9])
p <- paste(m[,1],m[,2])
t <- strptime(p, "%Y-%m-%d %H:%M:%S") #convert the date and time in the POSIXlt type
dev.set(3)
png(filename= "myplot3.png")
plot(t,type= "n", m$Sub_metering_1, ylab= "Energy sub metering")
lines(t, m$Sub_metering_1)
lines(t, m$Sub_metering_2, col="red")
lines(t, m$Sub_metering_3, col="blue")
legend("topright", legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col= c("black", "red", "blue"), lty=c(1,1,1))
dev.off()